[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
mongodb = "2.0.2"
serde = {version = "1.0", features = ["derive"] }
warp = "0.1.3"
bson = "0.12.2"